spring.application.name=TASTYCUISINE
server.port=8080

spring.datasource.url=jdbc:postgresql://db.ogqyymsnkhdsghtkmwbf.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=1sOOnqjItHmKQeSz
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=validate